version: '3'
services:
  dev:
    image: home_automation_server
    volumes:
      - nodemodules:/usr/src/service/node_modules
      - .:/apps/home_automation_server
    #working_dir: /apps/home_automation_server
    command: yarn start
    ports:
      - 3000:3000
volumes:
  nodemodules:
    external: true